<?php

namespace Walls\DtoBundle\Tests\Service\Extjs;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-11-08 at 06:42:42.
 */
class ExtjsDtoHandlerTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var ExtjsDtoHandler
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new ExtjsDtoHandler;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers Walls\DtoBundle\Service\Extjs\ExtjsDtoHandler::wrapData
     * @todo   Implement testWrapData().
     */
    public function testWrapData()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Walls\DtoBundle\Service\Extjs\ExtjsDtoHandler::wrapMessage
     * @todo   Implement testWrapMessage().
     */
    public function testWrapMessage()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Walls\DtoBundle\Service\Extjs\ExtjsDtoHandler::wrapException
     * @todo   Implement testWrapException().
     */
    public function testWrapException()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }
}
